### ISSUE TITLE
1.20.6 update checklist

### ISSUE THREAD

**Issue by libraryaddict** [libraryaddict/LibsDisguises#755]
The reason behind this update taking so long is that ProtocolLib hasn't been working as well as it had in the past (Not just for this update), and although it is an option to create PRs and whatnot, I've decided to instead switch to PacketEvents as per #752 

This is a checklist of tasks needing doing before this is complete.
This checklist does not promise a timeline of when things will be complete, as some tasks in this may be missing.
I would expect perhaps, 15th of June? 

The earliest builds are probably going to be ones you have to go out of the way for, I have little intention to roll out this update until I'm sastified with it. It promises to break plugins and if there's a bad enough bug, it'd break servers for no reason. After all, this is a massive switch to PacketEvents, and requires internals rewritten.

https://github.com/retrooper/packetevents

- [ ] Test 1.12
- [ ] Test 1.13
- [ ] Test 1.14
- [ ] Test 1.15
- [ ] Test 1.16
- [ ] Test 1.17
- [ ] Test 1.18
- [ ] Test 1.19
- [ ] Test 1.20.4
- [ ] Test 1.20.6
- [ ] Implement metadata grabbing from nms for all versions, DisguiseAPI method requires it
- [ ] Test villager professions / levels / etc
- [ ] Test Rabbit Type
- [ ] Test Particle Parsing
 - [ ] Example 1
- [ ] Test entity pose
- [ ] Test boat type / treespecies work decently for both old MC and newer (pre 1.19 and after)
- [ ] Add display brightness param type
- [ ] Verify gameprofile parsing is working seamlessly and loads
- [ ] Verify itemstack parsing is working properly, and serializes/deserializes properly
- [ ] Verify skin grabbing is working, may be other gameprofile related needing changes
- [ ] Verify player disguises in general is working properly
- [ ] Go over sounds again, may be missing something
- [ ] Implement better async support, may require a larger change of internals
- [ ] Possibly support that server (purpur or something?) that does threads per world
- [ ] Verify all disguises work
- [ ] Look into junit testing for as much as feasible, might be doable now? Namely converting param strings to params. Such as a string to particle. Mostly that tbh.
- [ ] Verify modded client stuff is working (The custom entities), may not be able to support it without demand
- [ ] Depend more on Components instead of simple strings. This is mostly in reference to entity custom name
- [ ] Migrate old ProtocolLib stuff to packet events
- [ ] Clean up the way we handle packets? It might be creating issues with packetevents. Such as cloning.
- [ ] Clarify the malware message to inform them that they have malware and what it probably is
- [ ] Implement new feature that removes disguise if you place or destroy a block (or related actions)

**Comment by andrewkm** [comment]
Goodluck on the packetevents switch!

**Comment by libraryaddict** [comment]
Small update for anyone who doesn't pay attention to the discord.
I have been putting some builds in there, currently it's just in a state of needing some testing done before I'll push it to jenkins as dev builds, which will start breaking plugins/putting it out there as a whole.

**Comment by libraryaddict** [comment]
Oh and the 1.21 new mobs, which I forgot to add and forgot to mention here. It has a basic level of support, so hopefully it's just a case of adding the accessors to the flagwatchers

**Comment by andrewkm** [comment]
@libraryaddict I seem to be getting an unstable issue with tests while compiling the latest:
https://gist.githubusercontent.com/andrewkm/c2f7e2d2ec045e79f0ec945936780d91/raw/9955a83d303a2dce843d5b24e477fbec97734c96/gistfile1.txt

Any idea what could be going on here, it is not an issue on md-5's jenkins however. Am confused...
I do have packetevents compiled from both their master & 2.0 branch.

**Comment by andrewkm** [comment]
> Best guess atm on mobile, is outdated code or dependencies

Hm, I'm compiling master for LibsDisguises, and 2.0 for PacketEvents.
File size seems to come out exactly the same as md-5's jenkins as well, just the tests are failing. Hm.

**Comment by libraryaddict** [comment]
Alright, fixed. Glad it's an issue I had seen before or this would've stumped me.

**Comment by andrewkm** [comment]
Confirmed fixed, thanks!

**Comment by libraryaddict** [comment]
Added a few TODO's and removed older TODO's that were cluttering & obsolete.

**Comment by libraryaddict** [comment]
The other feature that we will be waiting for is https://github.com/retrooper/packetevents/pull/866
Without it, servers using datapacks will break in the update. But it's likely to be ready long before I am.

**Comment by libraryaddict** [comment]
WIP list of things to do

- [ ] Migrate configs to a better structure
- [ ] Have hitbox setting scale with the scale attribute, both disguise and non-disguise
- [ ] Maybe need to have nametags follow vehicles, not sure if fixed or not
